Repository Bulebots/bulebule, pull requests merged in 2018-10, with the labels that each got.

#311 Fix outdated simulation client
  scripts/simulation_client.c
  src/simulation/move.c
  src/simulation/move.h
Labels: bug

#322 Do not flood unless required
  src/search.c
  src/search.h
  src/solve.c
Labels: enhancement

#327 Fix microcontroller reference and description
  docs/source/brain.rst
Labels: documentation, enhancement
