Repository Bulebots/bulebule, pull requests merged in 2018-03, with the labels that each got.

#204 Exceptions priorities
  docs/source/brain.rst
  docs/source/configuration.rst
  src/setup.c
  src/setup.h
Labels: bug, enhancement

#236 Remove analog gyro configuration
  src/detection.c
  src/detection.h
  src/setup.c
Labels: feature

#200 Real-time sensors visualization
  scripts/connect_bluetooth.py
  src/logging.c
  src/logging.h
Labels: feature

#237 Simple script to visualize emitters configuration
  requirements.txt
  scripts/emitters.py
Labels: feature

#185 Speed
  src/control.c
  src/move.c
Labels: enhancement

#242 Update software dependencies in the documentation
  docs/source/brain.rst
Labels: documentation

#243 Disable email notifications for Travis builds
  .travis.yml
Labels: enhancement
